# Generated by Django 4.2.7 on 2023-11-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
